name: PortalNetwork
on:
  push:
    branches: [master]
    tags: ['*']
  pull_request:
    types: [opened, reopened, synchronize]

env:
  cwd: ${{github.workspace}}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-unit-portalnetwork:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: jq -r '.workspaces |= .[0:2]' package.json
      - run: npm i --production-only --workspace=portalnetwork --workspace=proxy

      - run: npm run lint
        working-directory: ${{github.workspace}}/packages/portalnetwork
      - run: npm run test
        working-directory: ${{github.workspace}}/packages/portalnetwork

  test-integration-portalnetwork:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm i
        working-directory: ${{ github.workspace }}

      - run: npm run tape -- 'test/integration/wire.spec.ts'    

  
